[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "astronomeh"
version = "0.1.0"
description = "My astronomy helper package"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
   "numpy",
   "matplotlib",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
